package model

// Generated by https://quicktype.io

type GetProjectResponse struct {
	Status        string          `json:"status"`
	Data          *GetProjectData `json:"data"`
	CorrelationID string          `json:"correlationId"`
}

type GetProjectData struct {
	Project        *Project `json:"project"`
	CreatedAt      int64    `json:"createdAt"`
	LastModifiedAt int64    `json:"lastModifiedAt"`
	IsFavorite     bool     `json:"isFavorite"`
}

type Project struct {
	OrgIdentifier string `json:"orgIdentifier"`
	Identifier    string `json:"identifier"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Color         string `json:"color"`
}

type CreateProjectRequest struct {
	Project *Project `json:"project"`
}
