kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
  - go test -v
  - go build

trigger:
  event:
    - push

---
kind: pipeline
type: docker
name: release

steps:
- name: build-linux-amd64
  image: golang
  environment:
    GOOS: linux
    GOARCH: amd64
  commands:
    - go test -v
    - go build -o bin/harness-move-project-$GOOS-$GOARCH

- name: build-linux-arm64
  image: golang
  environment:
    GOOS: linux
    GOARCH: arm64
  commands:
    - go test -v
    - go build -o bin/harness-move-project-$GOOS-$GOARCH

- name: build-linux-386
  image: golang
  environment:
    GOOS: linux
    GOARCH: 386
  commands:
    - go test -v
    - go build -o bin/harness-move-project-$GOOS-$GOARCH

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github
    files:
      - bin/harness-move-project*

trigger:
  event:
    - tag
